version: "2"
services:
  web:
    image: chakrar27/contactsdemo:ext_con
    ports:
      - 8080:8080
    environment:
      - DB_NAME=mytestdb
      - DB_USER=postgres
      - DB_PASS=password
      - POSTGREDB_URL=jdbc:postgresql://192.168.99.100:5432
    depends_on: 
      - db 
  db:
    build: ./postgres
    ports:
      - "5432:5432"
    environment:
      - DB_NAME=mytestdb
      - DB_USER=postgres
      - DB_PASS=password
      - SCHEMA=iot 
  
